---
services:
  gateway:
    image: inductiveautomation/ignition:8.1.26
    ports:
      - 8088:8088 # HOST:CONTAINER
    volumes:
      - gateway-data:/usr/local/bin/ignition/data
    environment:
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=not-password
      - IGNITION_EDITION=standard
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n webinar-demo-gw

volumes:
  gateway-data:
