# Scale-Out Architecture Example
# https://inductiveautomation.com/ignition/architectures
# https://inductiveautomation.com/static/pdf/IgnitionArchitecture-ScaleOut.pdf
---
x-default-logging:
  &default-logging
  logging:
    options:
      max-size: '100m'
      max-file: '5'
    driver: json-file

x-ignition-opts:
  &ignition-opts
  <<: [ *default-logging ]
  image: inductiveautomation/ignition:${IGNITION_VERSION:-latest}
  env_file: gw-init/gateway.env
  secrets:
    - gateway-admin-password
  healthcheck:
    disable: true
  networks:
    - default
    - database

services:
  gateway-fe:
    <<: [ *ignition-opts ]
    hostname: gateway-fe
    command: >
      -n Ignition-frontend
      -m ${GATEWAY_MAX_MEMORY:-512}
      -r /restore.gwbk
    volumes:
      - gateway-fe-data:/usr/local/bin/ignition/data
      - ./gw-backup:/backup
      - ./gw-init/gateway-fe.gwbk:/restore.gwbk
      - ./gw-init/gateway-fe.uuid:/usr/local/bin/ignition/data/.uuid
      - ./gw-init/gateway-fe-metro-keystore:/usr/local/bin/ignition/webserver/metro-keystore
    labels:
      - traefik.enable=true

  gateway-tag1:
    <<: [ *ignition-opts ]
    hostname: gateway-tag1
    command: >
      -n Ignition-tag1
      -m ${GATEWAY_MAX_MEMORY:-512}
    environment:
      GATEWAY_NETWORK_0_HOST: gateway-fe
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
    volumes:
      - gateway-tag1-data:/usr/local/bin/ignition/data
      - ./gw-init/gateway-tag1.uuid:/usr/local/bin/ignition/data/.uuid
      - ./gw-init/gateway-tag1-metro-keystore:/usr/local/bin/ignition/webserver/metro-keystore
    labels:
      - traefik.enable=true

  gateway-tag2:
    <<: [ *ignition-opts ]
    hostname: gateway-tag2
    command: >
      -n Ignition-tag2
      -m ${GATEWAY_MAX_MEMORY:-512}
    environment:
      GATEWAY_NETWORK_0_HOST: gateway-fe
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
    volumes:
      - gateway-tag2-data:/usr/local/bin/ignition/data
      - ./gw-init/gateway-tag2.uuid:/usr/local/bin/ignition/data/.uuid
      - ./gw-init/gateway-tag2-metro-keystore:/usr/local/bin/ignition/webserver/metro-keystore
    labels:
      - traefik.enable=true

  db:
    <<: *default-logging
    image: mariadb:${MARIADB_VERSION:-latest}
    networks:
      - database
    ports:
      - 3306
    environment:
      MARIADB_USER: ignition
      MARIADB_PASSWORD_FILE: /run/secrets/db-ignition-password
      MARIADB_DATABASE: ignition
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    secrets:
      - db-root-password
      - db-ignition-password
    volumes:
      - db-data:/var/lib/mysql
    
secrets:
  gateway-admin-password:
    file: secrets/gateway-admin-password
  db-ignition-password:
    file: secrets/db-ignition-password
  db-root-password:
    file: secrets/db-root-password

networks:
  default:
    name: proxy
    external: true
  database:

volumes:
  gateway-fe-data:
  gateway-tag1-data:
  gateway-tag2-data:
  db-data:
